---
- name: Update Ubuntu server
  hosts: db
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Upgrade all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Reboot the server if needed
      ansible.builtin.reboot:
        reboot_timeout: 300
